Resources:
  DefaultQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.funktor.DefaultQueueName}
      VisibilityTimeout: ${self:custom.funktor.DefaultQueueHandler.visibilityTimeout}
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt": [ DefaultDeadLetterQueue, Arn ]
        maxReceiveCount: ${self:custom.funktor.DefaultQueueHandler.maxReceiveCount}
  DefaultDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.funktor.DefaultDeadJobQueueName}

Outputs:
  DefaultQueueUrl:
    Value:
      Ref: DefaultQueue
  DefaultDeadLetterQueueUrl:
    Value:
      Ref: DefaultDeadLetterQueue
