Resources:
  IncomingJobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.funktor.IncomingJobQueueName}
      VisibilityTimeout: ${self:custom.funktor.IncomingJobHandler.visibilityTimeout}
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt": [ IncomingJobDeadLetterQueue, Arn ]
        maxReceiveCount: ${self:custom.funktor.IncomingJobHandler.maxReceiveCount}
  IncomingJobDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.funktor.IncomingDeadJobQueueName}

Outputs:
  IncomingJobQueueUrl:
    Value:
      Ref: IncomingJobQueue
  IncomingJobDeadLetterQueueUrl:
    Value:
      Ref: IncomingJobDeadLetterQueue
