Resources:
  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.funktor.JobsTableName}
      AttributeDefinitions:
        - AttributeName: jobShard
          AttributeType: N
        - AttributeName: jobId
          AttributeType: S
        - AttributeName: category
          AttributeType: S
        - AttributeName: performAt
          AttributeType: S
        - AttributeName: dummy
          AttributeType: S
      KeySchema:
        - AttributeName: jobShard
          KeyType: HASH
        - AttributeName: jobId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: performAtIndex
          KeySchema:
          - AttributeName: dummy
            KeyType: HASH
          - AttributeName: performAt
            KeyType: RANGE
          Projection:
            NonKeyAttributes:
            - jobId
            - payload
            - category
            ProjectionType: INCLUDE
        - IndexName: categoryIndex
          KeySchema:
          - AttributeName: category
            KeyType: HASH
          - AttributeName: performAt
            KeyType: RANGE
          Projection:
            NonKeyAttributes:
            - jobId
            - payload
            - category
            ProjectionType: INCLUDE
      BillingMode: PAY_PER_REQUEST
      # Set the capacity based on the stage
      #ProvisionedThroughput:
        #ReadCapacityUnits: ${self:custom.tableThroughput}
        #WriteCapacityUnits: ${self:custom.tableThroughput}

Outputs:
  JobsTable:
    Value:
      Ref: JobsTable
