Resources:
  SingleThreadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.funktor.SingleThreadQueueName}
      VisibilityTimeout: ${self:custom.funktor.SingleThreadQueueHandler.visibilityTimeout}
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt": [ SingleThreadDeadLetterQueue, Arn ]
        maxReceiveCount: ${self:custom.funktor.SingleThreadQueueHandler.maxReceiveCount}
  SingleThreadDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.funktor.SingleThreadDeadJobQueueName}

Outputs:
  SingleThreadQueueUrl:
    Value:
      Ref: SingleThreadQueue
  SingleThreadDeadLetterQueueUrl:
    Value:
      Ref: SingleThreadDeadLetterQueue
